[package]
name = "archlogo"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "s"
codegen-units = 1
panic = "abort"
debug = false
rpath = false
strip = true

[dependencies]
anyhow = "1.0"
eframe = "0.21"
image = "0.24"
uname = "0.1"
